_target_: src.model.LightningModule

num_classes: 10

net:
  _target_: src.nets.resnet18.Resnet18
  num_classes: ${model.num_classes}

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True

  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true

  eta_min: 1e-6
