_target_: src.datamodules.CIFAR10DataModule

data_dir: ${core.data_dir}
num_classes: 10

train_transform:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.ToImage
    - _target_: torchvision.transforms.v2.ToDtype
      dtype: torch.float32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

batch_size: 512
num_workers: 8
